# Generate-SpawnReadme.ps1
# Generates a README.md summary for a spawned environment

param(
    [Parameter(Mandatory=$true)]
    [string]$UserPath,           # e.g., C:\Users\Lab1\.claude

    [Parameter(Mandatory=$true)]
    [string]$Username,

    [Parameter(Mandatory=$true)]
    [string]$Template,

    [string]$Identity,

    [string]$Projects,

    [string]$SpawnerRoot
)

# Get template description
$config = Get-Content (Join-Path $SpawnerRoot "config.json") -Raw | ConvertFrom-Json
$templateDesc = if ($config.templates.$Template) { $config.templates.$Template.description } else { $Template }

# Build identity section
$identitySection = ""
if ($Identity) {
    $identityPath = Join-Path $SpawnerRoot "identities\$Identity"
    $identitySection = @"

## From Identity ($Identity)
"@

    # Check for skills
    $skillsPath = Join-Path $identityPath "skills"
    if (Test-Path $skillsPath) {
        $skills = (Get-ChildItem $skillsPath -Directory).Name -join ", "
        if ($skills) {
            $identitySection += "`n- **Skills:** $skills"
        }
    }

    # Check for agents
    $agentsPath = Join-Path $identityPath "agents"
    if (Test-Path $agentsPath) {
        $agents = (Get-ChildItem $agentsPath -File -Filter "*.md").BaseName -join ", "
        if ($agents) {
            $identitySection += "`n- **Agents:** $agents"
        }
    }

    # Check for hooks
    $hooksPath = Join-Path $identityPath "hooks"
    if (Test-Path $hooksPath) {
        $hooks = (Get-ChildItem $hooksPath -File).Name -join ", "
        if ($hooks) {
            $identitySection += "`n- **Hooks:** $hooks"
        }
    }
}

# Build projects section
$projectsSection = ""
if ($Projects) {
    $projectsList = ($Projects -split ",").Trim() -join ", "
    $projectsSection = @"

## Projects Copied
$projectsList
"@
}

# Generate README content
$readme = @"
# Spawned Environment

**User:** $Username
**Created:** $(Get-Date -Format "yyyy-MM-dd HH:mm")
**Base:** $Template
$(if ($Identity) { "**Identity:** $Identity" })

## What's Included

### From Base ($Template)
$templateDesc
$identitySection
$projectsSection

## Getting Started

1. Open a command prompt as $Username`:
   ``````
   runas /user:$Username cmd
   ``````

2. Run Claude Code:
   ``````
   claude
   ``````

## Directory Structure

``````
C:\Users\$Username\
├── .claude\           # Claude Code configuration
│   ├── settings.json  # Permissions and settings
│   ├── skills\        # Available skills
│   ├── agents\        # Available agents
│   └── hooks\         # Automation hooks
└── projects\          # Your project workspace
``````

---
*Generated by Spawner v2 - Universal Identity System*
"@

$readmePath = Join-Path $UserPath "SPAWN-README.md"
$readme | Out-File $readmePath -Encoding UTF8 -Force

return $readmePath
