# User-Export.ps1 - Export sanitized user config for sharing
# Called by: spawner export <username> [--output <path>]
# ALWAYS runs sanitization - safe to share publicly

param(
    [Parameter(Mandatory=$true)]
    $Config,
    [Parameter(Mandatory=$true)]
    [string]$SpawnerRoot,
    [Parameter(Mandatory=$true)]
    [string]$Username,
    [string]$Output
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "ERROR" { "Red" }
        "WARN"  { "Yellow" }
        "OK"    { "Green" }
        "STEP"  { "Cyan" }
        default { "White" }
    }
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
}

# Validate user exists
$userHome = "C:\Users\$Username"
$userConfigDir = "$userHome\.claude"

if (-not (Test-Path $userConfigDir)) {
    Write-Log "User .claude directory not found: $userConfigDir" "ERROR"
    exit 1
}

Write-Log "========================================" "STEP"
Write-Log "  EXPORT (SANITIZED): $Username" "STEP"
Write-Log "========================================" "STEP"
Write-Log "Source: $userConfigDir" "INFO"

# Determine output path
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
if ($Output) {
    if ($Output -match "\.zip$") {
        $exportZip = $Output
        $exportDir = $Output -replace "\.zip$", ""
    } else {
        $exportDir = $Output
        $exportZip = "$Output.zip"
    }
} else {
    $exportsPath = Join-Path $SpawnerRoot $Config.backups.exportsPath
    if (-not (Test-Path $exportsPath)) {
        New-Item -ItemType Directory -Path $exportsPath -Force | Out-Null
    }
    $exportDir = Join-Path $exportsPath "$Username-export-$timestamp"
    $exportZip = "$exportDir.zip"
}

# Create temp directory for sanitization
$tempDir = Join-Path $env:TEMP "spawner-export-$(Get-Random)"
New-Item -ItemType Directory -Path $tempDir -Force | Out-Null

Write-Log "Sanitizing for safe sharing..." "STEP"

# Run sanitization pipeline
$sanitizeScript = Join-Path $SpawnerRoot "lib\Sanitize-Config.ps1"
$sanitizeResult = & $sanitizeScript -SourcePath $userConfigDir -DestPath $tempDir -Config $Config -Validate

if (-not $sanitizeResult.Success) {
    Write-Log "Sanitization failed!" "ERROR"
    foreach ($warn in $sanitizeResult.Warnings) {
        Write-Log "  $warn" "WARN"
    }
    Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue
    exit 1
}

# Generate export manifest
Write-Log "Generating export manifest..." "STEP"

$manifest = @{
    version = "3.0"
    type = "user-export"
    username = $Username
    exported = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    sanitized = $true
    sanitization = @{
        removedFiles = $sanitizeResult.RemovedFiles
        removedDirs = $sanitizeResult.RemovedDirs
        redactedFiles = $sanitizeResult.RedactedFiles
        pathsReplaced = $sanitizeResult.PathsReplaced
    }
    instructions = @"
This is a sanitized export from Spawner v3.

To import:
  spawner import $Username-export.zip <target-username>

Or manually copy to: C:\Users\<username>\.claude

Note: {USER_HOME} placeholders will be replaced during import.
"@
}

$manifest | ConvertTo-Json -Depth 10 | Out-File (Join-Path $tempDir "export-manifest.json") -Encoding UTF8

# Create README for the export
$readme = @"
# Spawner Export: $Username

Exported: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Contents

This is a sanitized Claude Code configuration export.

**Removed for security:**
- API keys and credentials
- Session data and cache
- Local paths (replaced with {USER_HOME})

## Import Instructions

### Using Spawner

```powershell
spawner import $Username-export.zip <target-username>
```

### Manual Import

1. Extract to: ``C:\Users\<username>\.claude``
2. Create ``.env`` with your API key: ``ANTHROPIC_API_KEY=sk-ant-api...``
3. Replace ``{USER_HOME}`` placeholders with actual paths

## What's Included

- Settings and permissions (settings.json)
- Skills and commands
- Agents and hooks
- CLAUDE.md configurations

## What's NOT Included

- API keys (.env)
- Session history
- Cache and temporary files
- User-specific paths

---
Generated by Spawner v3
"@

$readme | Out-File (Join-Path $tempDir "README.md") -Encoding UTF8

# Create zip archive
Write-Log "Creating zip archive..." "STEP"

# Ensure exports directory exists
$exportParent = Split-Path $exportZip -Parent
if (-not (Test-Path $exportParent)) {
    New-Item -ItemType Directory -Path $exportParent -Force | Out-Null
}

# Remove existing zip if present
if (Test-Path $exportZip) {
    Remove-Item $exportZip -Force
}

Compress-Archive -Path "$tempDir\*" -DestinationPath $exportZip -Force

# Cleanup temp
Remove-Item $tempDir -Recurse -Force

# Get zip size
$zipSize = (Get-Item $exportZip).Length
$zipSizeMB = [math]::Round($zipSize / 1MB, 2)

Write-Log "========================================" "OK"
Write-Log "  EXPORT COMPLETE" "OK"
Write-Log "  File: $exportZip" "OK"
Write-Log "  Size: $zipSizeMB MB" "OK"
Write-Log "========================================" "OK"
Write-Log "" "INFO"
Write-Log "This export is SAFE TO SHARE publicly." "INFO"
Write-Log "All secrets have been removed or redacted." "INFO"

return $exportZip
